# Generated by Django 6.0.2 on 2026-03-03 11:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('time', models.TimeField(blank=True, null=True)),
                ('repeat', models.BooleanField(default=False)),
                ('weekly', models.BooleanField(default=False)),
                ('monthly', models.BooleanField(default=False)),
                ('yearly', models.BooleanField(default=False)),
                ('weekly_options', models.JSONField(blank=True, default=list, null=True)),
                ('importance', models.CharField()),
                ('done', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
