# Generated by Django 6.0.2 on 2026-03-02 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_events_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='weekly_options',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
