# Generated by Django 6.0.2 on 2026-03-02 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_events_weekly_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
