# Generated by Django 6.0.2 on 2026-02-19 14:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gym_days', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MuscleGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(choices=[('CHEST', 'Chest'), ('BACK', 'Back'), ('TRICEPS', 'Triceps'), ('BICEPS', 'Biceps'), ('SHOULDERS', 'Shoulders'), ('FOREARM', 'Forearm'), ('TRAPS', 'Traps'), ('QUADS', 'Quads'), ('HAMSTRINGS', 'Hamstrings'), ('GLUTES', 'Glutes'), ('CALVES', 'Calves'), ('ADDUCTORS', 'Adductors'), ('ABDUCTORS', 'Abductors'), ('ABS', 'Abs')], default='GENERAL', max_length=20)),
                ('dia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='muscle_groups', to='gym.day')),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sets', models.IntegerField(default='1')),
                ('reps', models.IntegerField(default='1')),
                ('nome', models.CharField(max_length=100)),
                ('muscle_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='gym.musclegroup')),
            ],
        ),
    ]
