# Generated by Django 6.0.2 on 2026-02-19 21:58

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0002_alter_day_nome'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Day',
            new_name='DayPlan',
        ),
    ]
