# Generated by Django 6.0.2 on 2026-02-19 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0003_rename_day_dayplan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dayplan',
            old_name='nome',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='exercise',
            old_name='nome',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='musclegroup',
            old_name='dia',
            new_name='day',
        ),
        migrations.RenameField(
            model_name='musclegroup',
            old_name='nome',
            new_name='name',
        ),
    ]
