# Generated by Django 6.0.2 on 2026-02-23 14:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0004_rename_nome_dayplan_name_rename_nome_exercise_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DayPlan',
            new_name='Workouts',
        ),
    ]
