# Generated by Django 6.0.2 on 2026-02-23 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0005_rename_dayplan_workouts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workouts',
            old_name='name',
            new_name='day',
        ),
    ]
