# Generated by Django 6.0.2 on 2026-02-23 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0006_rename_name_workouts_day'),
    ]

    operations = [
        migrations.RenameField(
            model_name='musclegroup',
            old_name='day',
            new_name='workout',
        ),
    ]
