# Generated by Django 6.0.2 on 2026-02-23 18:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0007_rename_day_musclegroup_workout'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Workouts',
            new_name='Workout',
        ),
    ]
